### ISSUE TITLE
My gratitude

### ISSUE THREAD

**Issue by SteakOvercooked** [villapx/home#1]
Hey, this is not necessarily an issue, just wanted to say thank you for [your answer here](https://superuser.com/questions/1058474/increase-keyboard-repeat-rate-beyond-control-panel-limits-in-windows-10) as i do not have the reputation to upvote or leave a comment. It has helped me a lot and i appreciate your detailed explanation 😅

**Comment by villapx** [comment]
Lol you're very welcome! I'm happy to help out.

I had been wondering about increasing the keyboard repeat rate for _years_ now, and finally I decided to buckle down and dig through the documentation to figure out how it actually works. I'm glad it's been useful!!
